### ISSUE TITLE
[Expanded Storage-1.16.2] 'Select Screen Type' Button Overlaps with Inventory Profiles Buttons.

### ISSUE THREAD

**Issue by Gbergz** [NinjaPhenix/ForgeMods#9]
![netheritechest](https://user-images.githubusercontent.com/26634554/91915751-a46f0480-ecbb-11ea-8ed2-9c4c8622952a.PNG)

**Talking about this mod:** https://www.curseforge.com/minecraft/mc-mods/inventory-profiles

**Minecraft:** 1.16.2
**Forge:** 33.0.23
**Mod Version:** 3.0.3

**Comment by NinjaPhenix** [comment]
Thought I had already fixed this, maybe something changed ( or maybe it was on forge ).
Will take a look into it but it won't be added immediately as I'm working on a feature.

**Comment by NinjaPhenix** [comment]
Actually I'll just remove the button will make it easier for me, will move it to a config screen or something.

**Comment by NinjaPhenix** [comment]
Sorry it's been a while without a response.
I've moved the select container / settings button outside the main area of the screen so that hopefully it is less likely to conflict with other mods.

Example: 
![image](https://user-images.githubusercontent.com/5214513/93272753-2546f980-f7ae-11ea-9fd5-02794b02d9b9.png)

New build can be found on curseforge: https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge/files/3058044
